import fs from "node:fs";
import path from "node:path";
import os from "node:os";

import { MACHINE_DIR, projectToken } from "../config.js";

/**
 * Shared, side-effect-free machine helpers used by BOTH supervision modes:
 *   • manage.js  — pm2 / always-on service mode
 *   • session.js — harness-bound mode (daemon lives only while an agent codes)
 *
 * The single shared concern is the machine-global leaf node and its config.
 */

export { MACHINE_DIR, projectToken };
export const APPS_DIR = path.join(MACHINE_DIR, "apps");
export const SESSIONS_DIR = path.join(MACHINE_DIR, "sessions");
export const REGISTRY = path.join(MACHINE_DIR, "registry.json");
export const LEAF_CONF = path.join(MACHINE_DIR, "leaf.conf");
export const LEAF_STORE = path.join(MACHINE_DIR, "leaf-store");
export const LOG_DIR = path.join(MACHINE_DIR, "logs");
export const IDENTITY = path.join(MACHINE_DIR, "identity");
export const LEAF_PORT = 4222;
export const LEAF_APP = "team-sync-leaf";

export function ensureMachineDirs() {
  for (const d of [APPS_DIR, SESSIONS_DIR, LEAF_STORE, LOG_DIR]) {
    fs.mkdirSync(d, { recursive: true });
  }
}

export function ensureIdentity() {
  if (!fs.existsSync(IDENTITY)) {
    ensureMachineDirs();
    const id = os.hostname().replace(/[^A-Za-z0-9-]/g, "-") || "agent";
    fs.writeFileSync(IDENTITY, id + "\n");
  }
}

export function hubHost(hubUrl) {
  return String(hubUrl).replace(/^nats(-leaf)?:\/\//, "");
}

/** Render the machine leaf-node config with one remote per distinct hub. */
export function renderLeafConf(hubs = []) {
  const user = process.env.SYNC_HUB_USER || "agent";
  const pass = process.env.SYNC_HUB_PASSWORD || "";
  const uniq = [...new Set(hubs.filter(Boolean))];
  const remotes = uniq
    .map((h) => {
      const creds = pass ? `${user}:${pass}@` : "";
      return `    { url: "nats-leaf://${creds}${hubHost(h)}", account: "SYNC" }`;
    })
    .join("\n");

  return `# AUTO-GENERATED by team-sync — do not edit by hand.
server_name: team-sync-leaf-${os.hostname().replace(/[^a-zA-Z0-9]/g, "-")}
listen: 127.0.0.1:${LEAF_PORT}

jetstream {
  store_dir: "${LEAF_STORE.replace(/\\/g, "/")}"
  domain: leaf
  max_file_store: 1GB
}

leafnodes {
${uniq.length ? `  remotes: [\n${remotes}\n  ]` : "  # no active hubs yet — local-only until a project is enrolled/active"}
}

http_port: 8223
`;
}

export function writeLeafConf(hubs = []) {
  ensureMachineDirs();
  fs.writeFileSync(LEAF_CONF, renderLeafConf(hubs));
  return [...new Set(hubs.filter(Boolean))];
}

export function readRegistry() {
  try {
    return JSON.parse(fs.readFileSync(REGISTRY, "utf8"));
  } catch {
    return { projects: [] };
  }
}

export function writeRegistry(reg) {
  ensureMachineDirs();
  fs.writeFileSync(REGISTRY, JSON.stringify(reg, null, 2) + "\n");
}
